# Generated by Django 4.1.7 on 2023-04-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('images', models.ImageField(upload_to='uploads/', verbose_name='Фотография')),
                ('family_status', models.CharField(choices=[('single', 'Холост'), ('divorced', 'Разведен'), ('actively_looking', 'В активном поиске'), ('married', 'В браке')], max_length=50, verbose_name='Семейное положение')),
                ('children', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=50, verbose_name='Наличие детей')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('life_with_mom', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('with_me', 'Мама живет со мной')], max_length=50, verbose_name='Живешь ли ты с мамой?')),
                ('addictions', models.CharField(choices=[('smoking', 'Курение'), ('alcohol', 'Алкоголь'), ('gambling', 'Лудомания')], max_length=50, verbose_name='Вредные привычки')),
                ('date_of_birthday', models.DateField(verbose_name='Дата рождения')),
                ('height', models.PositiveIntegerField(verbose_name='Рост')),
                ('taboo', models.TextField(max_length=1000, verbose_name='Табу')),
                ('dating', models.CharField(choices=[('hookup', 'Одна встреча'), ('meetings', 'Регулярные встречи'), ('relationships', 'Серьезные отношения'), ('communication', 'Общение')], max_length=100, verbose_name='Цель знакомств')),
                ('hobbies', models.TextField(max_length=1000, verbose_name='Увлечения')),
                ('zodiac_sign', models.CharField(choices=[('Capricorn', 'Козерог'), ('Aquarius', 'Водолей'), ('Pisces', 'Рыбы'), ('Aries', 'Овен'), ('Taurus', 'Телец'), ('Gemini', 'Близнецы'), ('Cancer', 'Рак'), ('Leo', 'Лев'), ('Virgo', 'Дева'), ('Libra', 'Весы'), ('Scorpio', 'Скорпион'), ('Ophiuchus', 'Змееносец'), ('Sagittarius', 'Стрелец')], max_length=100, verbose_name='Знак зодиака')),
                ('gender', models.CharField(choices=[('w', 'ж'), ('m', 'м')], max_length=100, verbose_name='Пол')),
                ('about_me', models.TextField(max_length=1000, verbose_name='Обо мне...')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
    ]
